
drop table ORDERS;
drop table PRODUCTS;
drop table SUPPLIERS;
drop table CUSTOMERS;
drop table EMPLOYEES;


CREATE TABLE CUSTOMERS
(
	CUSTOMER_ID INT PRIMARY KEY,
	FIRST_NAME VARCHAR2(20) ,
	LAST_NAME VARCHAR2(20) ,	
    GENDER  VARCHAR2(20) CHECK (GENDER IN ('Male','Female','Other')),		
	CUSTOMER_EMAIL VARCHAR2(20) ,	
    CUSTOMER_PHONE VARCHAR2(20) ,
	PREMIUM NUMBER(1) 	
);



CREATE TABLE EMPLOYEES
(
    EMPLOYEE_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR2(20) ,
    LAST_NAME VARCHAR2(20) ,
    GENDER  VARCHAR2(20) CHECK (GENDER IN ('Male','Female','Other')),
    EMPLOYEE_EMAIL VARCHAR2(30) ,
    EMPLOYEE_PHONE VARCHAR2(20) ,
    SALARY NUMBER,
    PROVISION INT 
);



CREATE TABLE SUPPLIERS
(
	SUPPLIER_ID INT PRIMARY KEY NOT NULL,
    SUPPLIER_NAME VARCHAR2(20),
	SUPPLIER_COUNTRY VARCHAR2(20)	
);



CREATE TABLE PRODUCTS
(
	PRODUCT_ID INT PRIMARY KEY NOT NULL,
	SUPPLIER_ID INT NOT NULL,
    CRYSTAL_NAME VARCHAR2(20),
    price_per_gram INT,
    colour VARCHAR2(20),
    
    CONSTRAINT FK1 FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS(SUPPLIER_ID)
);



CREATE TABLE ORDERS
(
	ORDER_ID INT PRIMARY KEY NOT NULL,
	PRODUCT_ID INT NOT NULL,
	CUSTOMER_ID INT NOT NULL,	
    EMPLOYEE_ID INT NOT NULL,
	ORDER_DATE DATE,
    PRODUCT_WEIGHT INT,
    PRICE INT,
	
	CONSTRAINT FK2 FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
	CONSTRAINT FK3 FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
    CONSTRAINT FK4 FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);


