
SET SERVEROUTPUT ON;

SELECT * FROM EMPLOYEES;
SELECT * FROM PRODUCTS;
SELECT * FROM SUPPLIERS;
SELECT * FROM CUSTOMERS;
SELECT * FROM ORDERS;



--PROCEDURA DO USTAWIENIA CENY PO INSERTOWANIU------
CREATE OR REPLACE PROCEDURE OCS
IS
P_P_G PRODUCTS.price_per_gram%TYPE;
CURSOR ORD IS SELECT PRODUCT_ID,ORDER_ID,PRODUCT_WEIGHT FROM ORDERS;
BEGIN
    FOR OS IN ORD
    LOOP
    SELECT price_per_gram INTO P_P_G FROM PRODUCTS WHERE PRODUCT_ID=OS.PRODUCT_ID;
    UPDATE ORDERS
    SET PRICE=CALCULATE_ORDER_PRICE(OS.PRODUCT_WEIGHT,P_P_G)
    WHERE ORDER_ID=OS.ORDER_ID;
    END LOOP;
END;


EXEC OCS;

-----OBLICZANIE CENY-----------------------------------
CREATE OR REPLACE FUNCTION CALCULATE_ORDER_PRICE
(WEIGHT in orders.product_weight%TYPE, PRICE IN products.price_per_gram%TYPE)
RETURN ORDERS.price%TYPE
IS
RET ORDERS.price%TYPE := 0;
BEGIN
    IF(WEIGHT > 0 AND PRICE > 0) THEN
        RET := WEIGHT*PRICE;
    END IF;
    RETURN RET;
END;

---------SEKWENCJA----------------------------------------
CREATE SEQUENCE ORDERS_SEQ
    START WITH 51
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE
    CACHE 20;


---------DODAWANIE ORDERA---------------------------------
CREATE OR REPLACE PROCEDURE ADD_ORDER
(C_ID IN customers.customer_id%TYPE, E_ID IN employees.employee_id%TYPE, P_ID IN products.product_id%TYPE, P_WEIGHT IN orders.product_weight%TYPE)
IS
PRICE orders.price%TYPE;
IF_PREM CUSTOMERS.PREMIUM%TYPE;
PREMIUM_DISCOUNT NUMBER:=1;
PROV EMPLOYEES.PROVISION%TYPE;
FLAG NUMBER:=0;
PER_G_PRICE PRODUCTS.price_per_gram%TYPE;
CURSOR EMPS IS SELECT EMPLOYEE_ID FROM EMPLOYEES;
CURSOR CUSTOMS IS SELECT CUSTOMER_ID FROM CUSTOMERS;
CURSOR PRODUCS IS SELECT PRODUCT_ID FROM PRODUCTS;
NO_E EXCEPTION;
NO_P EXCEPTION;
NO_C EXCEPTION;
BEGIN
    FOR EP IN EMPS
    LOOP
        IF(EP.EMPLOYEE_ID = E_ID) THEN
            FLAG:=1;
        END IF;
    END LOOP;
    IF(FLAG=0) THEN
        RAISE NO_E;
    END IF;
    FLAG:=0;
    FOR CU IN CUSTOMS
    LOOP
        IF(CU.CUSTOMER_ID = C_ID) THEN
            FLAG:=1;
        END IF;
    END LOOP;
    IF(FLAG=0) THEN
        RAISE NO_C;
    END IF;
    FLAG:=0;
    FOR PR IN PRODUCS
    LOOP
        IF(PR.PRODUCT_ID = P_ID) THEN
            FLAG:=1;
        END IF;
    END LOOP;
    IF(FLAG=0) THEN
        RAISE NO_P;
    END IF;
    
    SELECT PROVISION INTO PROV FROM EMPLOYEES WHERE EMPLOYEE_ID = E_ID;
    SELECT PREMIUM INTO IF_PREM FROM CUSTOMERS WHERE CUSTOMER_ID = C_ID;
    SELECT price_per_gram INTO PER_G_PRICE FROM PRODUCTS WHERE PRODUCT_ID=P_ID;
    
    IF(IF_PREM=1) THEN
        PREMIUM_DISCOUNT:= 0.95;
    END IF;
    
    PRICE:= CALCULATE_ORDER_PRICE(P_WEIGHT,PER_G_PRICE) * (1+PROV/100) * PREMIUM_DISCOUNT;
    INSERT INTO ORDERS VALUES ( ORDERS_SEQ.nextval , P_ID , C_ID , E_ID , SYSDATE, P_WEIGHT,PRICE);
    
    
    EXCEPTION
    WHEN NO_E THEN
    dbms_output.put_line('NO SUCH A EMPLOYEE');  
    WHEN NO_P THEN
    dbms_output.put_line('NO SUCH A PRODUCT');  
    WHEN NO_C THEN
    dbms_output.put_line('NO SUCH A CUSTOMER'); 
    WHEN OTHERS THEN
    dbms_output.put_line(SQLERRM);
END;

EXEC ADD_ORDER( 12, 2, 322 , 4);

SET SERVEROUTPUT ON;

SELECT * FROM ORDERS;

